"""
Isaac Lab DirectRLEnv — Spot Navigation
=========================================
Replaces mjx_nav_env.py. Uses PhysX 5 (GPU) for physics and
Isaac Sim RTX cameras for depth rendering.

This is the main environment class that Isaac Lab's training loop interacts with.
"""

from __future__ import annotations

import math
import torch

from .config import (
    JOINT_LOWER, JOINT_UPPER, STANDING_POSE, TARGET_HEIGHT,
    N_CAMS, CAM_H, CAM_W, MIN_DEPTH, MAX_DEPTH,
    N_OBS, N_STATIC, N_DYNAMIC, N_HUMANOID, HUMANOID_MOCAP_IDX,
    HUMANOID_OBSTACLE, PROPRIO_DIM, ACTION_DIM,
    OBS_HALF_SIZES, PATCH_HALF, ROOM_HALF, FLAT_TERRAIN_ROW_MAX,
)

# Scene keys matching the names generated by _build_obstacle_cfgs() in spot_env_cfg.py
_OBS_SCENE_KEYS = (
    [f"obs_static_{i:02d}" for i in range(N_STATIC)]
    + [f"obs_dynamic_{i:02d}" for i in range(N_DYNAMIC)]
    + ["obs_humanoid"]
)
from .reward import compute_reward, check_termination

try:
    from isaaclab.envs import DirectRLEnv
    from .spot_env_cfg import SpotNavEnvCfg
    HAS_ISAAC = True
except ImportError:
    try:
        from omni.isaac.lab.envs import DirectRLEnv
        from .spot_env_cfg import SpotNavEnvCfg
        HAS_ISAAC = True
    except ImportError:
        HAS_ISAAC = False


if HAS_ISAAC:

    class SpotNavEnv(DirectRLEnv):
        """
        Batched Spot navigation environment for Isaac Lab.

        Observations:
            depth:  (num_envs, 5, 120, 160) from RTX cameras
            proprio: (num_envs, 37) proprioception

        Actions:
            (num_envs, 12) normalized joint position targets in [-1, 1]
        """

        cfg: SpotNavEnvCfg

        def __init__(self, cfg: SpotNavEnvCfg, **kwargs):
            super().__init__(cfg, **kwargs)

            # Cache joint limit tensors on device
            self._joint_lower = torch.tensor(
                JOINT_LOWER, device=self.device, dtype=torch.float32
            )
            self._joint_upper = torch.tensor(
                JOINT_UPPER, device=self.device, dtype=torch.float32
            )
            self._joint_mid   = (self._joint_upper + self._joint_lower) / 2.0
            self._joint_range = (self._joint_upper - self._joint_lower) / 2.0
            # Action centre: standing pose so action=0 → robot stands still.
            # Using joint_mid as centre meant action=0 produced a non-standing
            # configuration, and random actions (std=1) applied ~800 Nm torques
            # on the first step, immediately knocking the robot over.
            self._action_center = torch.tensor(
                STANDING_POSE, device=self.device, dtype=torch.float32
            )

            # Goal positions (randomized per env on reset)
            self._goal_pos = torch.zeros(
                self.num_envs, 2, device=self.device
            )
            # Previous distance to goal (for progress reward)
            self._prev_dist = torch.zeros(self.num_envs, device=self.device)
            # Previous action (for smoothness reward)
            self._prev_action = torch.zeros(
                self.num_envs, ACTION_DIM, device=self.device
            )
            # Step counter
            self._step_count = torch.zeros(
                self.num_envs, device=self.device, dtype=torch.int32
            )

            # Humanoid patrol state
            self._human_pos = torch.zeros(self.num_envs, 2, device=self.device)
            self._human_wp_idx = torch.zeros(
                self.num_envs, device=self.device, dtype=torch.int32
            )

            # Obstacle positions: (num_envs, N_OBS, 3)
            # Mirrors MJX mocap_pos — tracks where obstacles are for reward distance
            self._obs_pos = torch.zeros(
                self.num_envs, N_OBS, 3, device=self.device
            )

            # Previous state caches (for reward computation)
            self._prev_root_pos = torch.zeros(
                self.num_envs, 3, device=self.device
            )
            self._prev_root_pos[:, 2] = TARGET_HEIGHT
            self._prev_prev_action = torch.zeros(
                self.num_envs, ACTION_DIM, device=self.device
            )

            # Default obstacle z-heights for resetting off-scene obstacles
            self._obs_default_z = torch.tensor(
                [hs[2] for hs in OBS_HALF_SIZES], device=self.device
            )

            # Cached joint targets (set in _pre_physics_step, applied in _apply_action)
            self._ctrl = torch.zeros(
                self.num_envs, ACTION_DIM, device=self.device
            )

        # ── Reset ────────────────────────────────────────────────────
        def _reset_idx(self, env_ids: torch.Tensor):
            """Reset selected environments."""
            super()._reset_idx(env_ids)
            n = len(env_ids)

            # World-space origin for each env — each env lives at a different
            # position in the world (tiled by env_spacing = PATCH_SIZE).
            # All robot/goal/obstacle positions must be expressed in world space.
            env_origins = self.scene.env_origins[env_ids]  # (n, 3)

            # ── Robot: random patch-local position ───────────────────
            robot_local_xy = torch.empty(n, 2, device=self.device).uniform_(
                -PATCH_HALF, PATCH_HALF
            )
            robot_yaw = torch.empty(n, device=self.device).uniform_(
                0.0, 2 * math.pi
            )

            root_state = self.scene["robot"].data.default_root_state[env_ids].clone()
            root_state[:, 0] = env_origins[:, 0] + robot_local_xy[:, 0]
            root_state[:, 1] = env_origins[:, 1] + robot_local_xy[:, 1]
            root_state[:, 2] = env_origins[:, 2] + TARGET_HEIGHT
            root_state[:, 3] = torch.cos(robot_yaw / 2)  # qw
            root_state[:, 4] = 0.0                        # qx
            root_state[:, 5] = 0.0                        # qy
            root_state[:, 6] = torch.sin(robot_yaw / 2)  # qz
            self.scene["robot"].write_root_state_to_sim(root_state, env_ids)

            # ── Joint reset ──────────────────────────────────────────
            joint_pos = torch.tensor(
                STANDING_POSE, device=self.device, dtype=torch.float32
            ).unsqueeze(0).expand(n, -1)
            joint_vel = torch.zeros(n, ACTION_DIM, device=self.device)
            self.scene["robot"].write_joint_state_to_sim(
                joint_pos, joint_vel, env_ids=env_ids
            )

            # ── Goal: patch-local, 1.5-3.5m from robot ──────────────
            goal_dist = torch.empty(n, device=self.device).uniform_(1.5, 3.5)
            goal_ang  = torch.empty(n, device=self.device).uniform_(0.0, 2 * math.pi)
            goal_local_xy = (robot_local_xy + torch.stack([
                goal_dist * torch.cos(goal_ang),
                goal_dist * torch.sin(goal_ang),
            ], dim=-1)).clamp(-PATCH_HALF, PATCH_HALF)
            goal_world_xy = env_origins[:, :2] + goal_local_xy
            robot_world_xy = env_origins[:, :2] + robot_local_xy

            self._goal_pos[env_ids] = goal_world_xy
            self._prev_dist[env_ids] = torch.linalg.norm(
                goal_world_xy - robot_world_xy, dim=-1
            )
            self._prev_action[env_ids] = 0.0
            self._step_count[env_ids] = 0

            # ── Obstacles: world-space, flat terrain only ────────────
            # Determine if each env is on a flat terrain row (≤ FLAT_TERRAIN_ROW_MAX).
            # If terrain is unavailable (flat-plane fallback), treat all as flat.
            try:
                terrain_levels = self.scene.terrain.terrain_levels[env_ids]
                is_flat = terrain_levels <= FLAT_TERRAIN_ROW_MAX  # (n,) bool
            except (AttributeError, TypeError, KeyError):
                is_flat = torch.ones(n, device=self.device, dtype=torch.bool)

            # Random local XY within patch (keep 0.5 m clear of edge)
            obs_local_xy = torch.empty(n, N_OBS, 2, device=self.device).uniform_(
                -(PATCH_HALF - 0.5), PATCH_HALF - 0.5
            )
            obs_z = self._obs_default_z.unsqueeze(0).expand(n, -1).unsqueeze(-1)
            # World-space obstacle positions
            obs_pos_new = (
                torch.cat([obs_local_xy, obs_z], dim=-1)       # (n, N_OBS, 3) local
                + env_origins.unsqueeze(1)                      # → world space
            )

            # Send obstacles off-scene on non-flat terrain
            OFF_SCENE = torch.tensor([1000.0, 0.0, 0.5], device=self.device)
            is_flat_3 = is_flat.unsqueeze(-1).expand(-1, 3)     # broadcast to (n,3)
            for i in range(N_STATIC + N_DYNAMIC):
                obs_pos_new[:, i] = torch.where(is_flat_3, obs_pos_new[:, i], OFF_SCENE)

            # Humanoid slot is always off-scene (disabled in terrain curriculum)
            if N_HUMANOID > 0:
                obs_pos_new[:, HUMANOID_MOCAP_IDX] = OFF_SCENE

            self._obs_pos[env_ids] = obs_pos_new
            self._human_pos[env_ids] = OFF_SCENE[:2]
            self._human_wp_idx[env_ids] = 0

            self._write_obstacle_poses_to_sim(env_ids)

        # ── Sync obstacles to PhysX ────────────────────────────────
        def _write_obstacle_poses_to_sim(self, env_ids: torch.Tensor):
            """Write self._obs_pos positions to PhysX rigid body root states.

            Each obstacle is a separate RigidObject in the scene. We write a
            root state tensor [pos(3) + quat(4) + lin_vel(3) + ang_vel(3) = 13]
            for each one.  Kinematic bodies ignore velocities, but the API
            requires the full 13-dim state.
            """
            n = len(env_ids)
            identity_quat = torch.tensor(
                [1.0, 0.0, 0.0, 0.0], device=self.device
            )

            for obs_idx, key in enumerate(_OBS_SCENE_KEYS):
                root_state = torch.zeros(n, 13, device=self.device)
                root_state[:, :3] = self._obs_pos[env_ids, obs_idx]
                root_state[:, 3:7] = identity_quat  # no rotation
                self.scene[key].write_root_state_to_sim(root_state, env_ids)

        # ── Observations ─────────────────────────────────────────────
        def _get_observations(self) -> dict:
            """Build observation dict with depth + proprio."""
            robot = self.scene["robot"]

            # ── Depth from RTX cameras ───────────────────────────────
            cam_names = [
                "cam_front_center", "cam_front_left", "cam_front_right",
            ]
            depth_list = []
            for name in cam_names:
                cam = self.scene[name]
                # distance_to_camera: (num_envs, H, W, 1) -> (num_envs, 1, H, W)
                d = cam.data.output["distance_to_camera"]
                d = d.permute(0, 3, 1, 2)  # channels first
                d = torch.clamp(d, MIN_DEPTH, MAX_DEPTH)
                depth_list.append(d)

            depth = torch.cat(depth_list, dim=1)  # (num_envs, 5, H, W)

            # ── Proprioception (37-dim) ──────────────────────────────
            root_pos  = robot.data.root_pos_w           # (B, 3)
            root_quat = robot.data.root_quat_w          # (B, 4) [w,x,y,z]
            root_linv = robot.data.root_lin_vel_w       # (B, 3)
            root_angv = robot.data.root_ang_vel_w       # (B, 3)
            joint_pos = robot.data.joint_pos             # (B, 12)
            joint_vel = robot.data.joint_vel             # (B, 12)

            # Goal direction and distance
            goal_diff = self._goal_pos - root_pos[:, :2]
            goal_dist = torch.linalg.norm(
                goal_diff, dim=-1, keepdim=True
            )
            goal_dir = goal_diff / (goal_dist + 1e-8)

            # Scale to ~[-1, 1] range (same scaling as JAX version)
            proprio = torch.cat([
                joint_pos / 3.14,       # 12
                joint_vel / 20.0,       # 12
                root_quat,              # 4
                root_linv / 5.0,        # 3
                root_angv / 10.0,       # 3
                goal_dir,               # 2
                goal_dist / 5.0,        # 1
            ], dim=-1)                  # 37-dim

            # Sanitize
            proprio = torch.where(
                torch.isfinite(proprio), proprio, torch.zeros_like(proprio)
            )
            proprio = torch.clamp(proprio, -10.0, 10.0)

            return {"depth": depth, "proprio": proprio}

        # ── Actions ──────────────────────────────────────────────────
        def _pre_physics_step(self, actions: torch.Tensor):
            """Convert normalized [-1,1] actions to joint targets (called once per control step)."""
            actions = torch.clamp(actions, -1.0, 1.0)
            actions = torch.where(
                torch.isfinite(actions), actions, torch.zeros_like(actions)
            )
            # Denormalize to joint position targets; cache for _apply_action
            self._ctrl = self._action_center + actions * self._joint_range
            self._prev_action = self._ctrl

        def _apply_action(self):
            """Write cached joint targets to the simulation (called each physics substep)."""
            self.scene["robot"].set_joint_position_target(self._ctrl)

        # ── Rewards ──────────────────────────────────────────────────
        def _get_rewards(self) -> torch.Tensor:
            robot = self.scene["robot"]
            root_pos  = robot.data.root_pos_w
            root_quat = robot.data.root_quat_w
            joint_vel = robot.data.joint_vel
            robot = self.scene["robot"]
            root_lin_vel = robot.data.root_lin_vel_w

            # Update humanoid position in obstacle array
            # Humanoid is disabled; keep its _obs_pos slot far off-scene so
            # it doesn't affect the distance computation.
            if N_HUMANOID > 0:
                self._obs_pos[:, HUMANOID_MOCAP_IDX] = 1000.0

            # Compute min obstacle distance (same math as MJX version)
            robot_xy = root_pos[:, :2]                                         # (B, 2)
            obs_xy = self._obs_pos[:, :, :2]                                   # (B, N_OBS, 2)
            dists = torch.linalg.norm(
                obs_xy - robot_xy.unsqueeze(1), dim=-1
            )                                                                  # (B, N_OBS)
            min_obs_dist = dists.min(dim=-1).values                            # (B,)
            has_collision = min_obs_dist < 0.35

            reward, self._reward_info, new_dist = compute_reward(
                robot_pos      = root_pos,
                robot_quat     = root_quat,
                goal_pos       = self._goal_pos,
                prev_robot_pos = self._prev_root_pos,
                joint_vel      = joint_vel,
                root_lin_vel   = root_lin_vel,
                action         = self._prev_action,
                prev_action    = self._prev_prev_action,
                min_obs_dist   = min_obs_dist,
                has_collision  = has_collision,
                prev_dist_goal = self._prev_dist,    
            )

            # Forward reward components to self.extras so ppo.py can read them
            # from the step_info dict (Isaac Lab returns self.extras as the 5th
            # element of step(), not a _get_info() callback)
            for k, v in self._reward_info.items():
                if isinstance(v, torch.Tensor):
                    self.extras[k] = v

            self._prev_dist = new_dist
            self._step_count += 1
            return reward

        # ── Info (reward components for diagnostics) ─────────────────
        def _get_info(self) -> dict:
            """Forward per-step reward components to the step info dict."""
            return getattr(self, '_reward_info', {})

        # ── Termination ──────────────────────────────────────────────
        def _get_dones(self) -> tuple[torch.Tensor, torch.Tensor]:
            robot = self.scene["robot"]
            root_pos  = robot.data.root_pos_w
            root_quat = robot.data.root_quat_w

            terminated = check_termination(
                root_pos, root_quat, self._goal_pos, self._step_count
            )

            # Truncation: timeout handled inside check_termination,
            # but Isaac Lab wants it separate
            truncated = self._step_count >= 1000

            # Remove timeout from terminated (it's a truncation, not failure)
            terminated = terminated & ~truncated

            return terminated, truncated

        def _post_physics_step(self):
            """Cache previous state for reward computation."""
            robot = self.scene["robot"]
            self._prev_root_pos = robot.data.root_pos_w.clone()
            self._prev_prev_action = self._prev_action.clone()

            # Update humanoid patrol and sync its rigid body to PhysX
            if HUMANOID_OBSTACLE["enabled"]:
                self._update_humanoid_patrol()
                self._sync_humanoid_to_sim()

        def _update_humanoid_patrol(self):
            """Move humanoid obstacle along patrol path near goal."""
            step_dt = HUMANOID_OBSTACLE.get("speed", 0.8) * 0.02  # control_dt
            patrol_r = HUMANOID_OBSTACLE["patrol_radius"]

            wp0 = torch.stack([
                torch.clamp(self._goal_pos[:, 0] + patrol_r, -ROOM_HALF, ROOM_HALF),
                torch.clamp(self._goal_pos[:, 1], -ROOM_HALF, ROOM_HALF),
            ], dim=-1)
            wp1 = torch.stack([
                torch.clamp(self._goal_pos[:, 0] - patrol_r, -ROOM_HALF, ROOM_HALF),
                torch.clamp(self._goal_pos[:, 1], -ROOM_HALF, ROOM_HALF),
            ], dim=-1)
            waypoints = torch.stack([wp0, wp1], dim=1)  # (B, 2, 2)

            env_idx = torch.arange(self.num_envs, device=self.device)
            target = waypoints[env_idx, self._human_wp_idx]

            diff = target - self._human_pos
            dist_h = torch.linalg.norm(diff, dim=-1, keepdim=True)
            dir_h  = diff / (dist_h + 1e-8)

            speed = HUMANOID_OBSTACLE["speed"]
            self._human_pos = torch.clamp(
                self._human_pos + dir_h * speed * 0.02,
                -ROOM_HALF, ROOM_HALF,
            )

            switch_dist = HUMANOID_OBSTACLE["wp_switch_dist"]
            self._human_wp_idx = torch.where(
                dist_h.squeeze(-1) < switch_dist,
                1 - self._human_wp_idx,
                self._human_wp_idx,
            )

        def _sync_humanoid_to_sim(self):
            """Write humanoid patrol position to its PhysX rigid body every step."""
            all_ids = torch.arange(self.num_envs, device=self.device)
            root_state = torch.zeros(self.num_envs, 13, device=self.device)
            root_state[:, 0] = self._human_pos[:, 0]
            root_state[:, 1] = self._human_pos[:, 1]
            root_state[:, 2] = HUMANOID_OBSTACLE["mocap_z"]
            root_state[:, 3] = 1.0  # qw (identity quaternion)
            self.scene["obs_humanoid"].write_root_state_to_sim(
                root_state, all_ids
            )

else:
    # Stub when Isaac Lab is not available
    class SpotNavEnv:
        """Stub — install Isaac Lab to use this environment."""
        def __init__(self, *args, **kwargs):
            raise ImportError(
                "SpotNavEnv requires NVIDIA Isaac Lab. "
                "Install Isaac Lab: https://isaac-sim.github.io/IsaacLab/"
            )
